<?xml version = "1.0" encoding="UTF-8"?>
<!DOCTYPE  Arboles[
        <!ELEMENT Arboles (Informacion)>
        <!ELEMENT Informacion (Arbol+)>
        <!ELEMENT Arbol (NombreCientifico*, NombreComun*, Vegetacion* ,Altura*, Forma*, ColorP*, ColorO*, Resistencia*)>
        <!ELEMENT NombreCientifico (#PCDATA)>
        <!ELEMENT NombreComun (#PCDATA)>
        <!ELEMENT Vegetacion (#PCDATA)>
        <!ELEMENT Altura (#PCDATA)>
        <!ELEMENT Forma (#PCDATA)>
        <!ELEMENT ColorP (#PCDATA)>
        <!ELEMENT ColorO (#PCDATA)>
        <!ELEMENT Resistencia (#PCDATA)>
        ]>
<Arboles>
        <Informacion>
                <Arbol>
                        <NombreCientifico>Acer monspessulanum</NombreCientifico>
                        <NombreComun>Arce de Montpellier, Arce menor</NombreComun>
                        <Vegetacion>Caducifolio</Vegetacion>
                        <Altura>De 6 a 10 metros</Altura>
                        <Forma>Copa esferica. Tronco principal recto con bifurcaciones. Ramaje colgante</Forma>
                        <ColorP>Haz verde brillante, enves verde blanquecino</ColorP>
                        <Resistencia>Heladas fuertes (Hasta -15째C)</Resistencia>
                </Arbol>
                <Arbol>
                        <NombreCientifico>Olea Europea</NombreCientifico>
                        <NombreComun>Olivo</NombreComun>
                        <Vegetacion>Perenne</Vegetacion>
                        <Altura>De 8 a 15 metros</Altura>
                        <Forma>Copa irregular, Tronco principal irregular con bifurcaciones</Forma>
                </Arbol>
                <Arbol>
                        <NombreCientifico>Ramaje tortuoso</NombreCientifico>
                        <ColorP>Haz verde oscuro, enves verde plateado</ColorP>
                        <Resistencia>Heladas medias(hasta -10째C)</Resistencia>
                </Arbol>
                <Arbol>
                        <NombreCientifico>Platanus Orientalis</NombreCientifico>
                        <Vegetacion>Caducifolio</Vegetacion>
                        <Altura>De 20 a 25 metros</Altura>
                        <Forma>Copa ovoidal. Tronco principal recto. Remaje expandido</Forma>
                        <ColorP>Haz verde medio. enves verde claro</ColorP>
                        <ColorO>Ocre</ColorO>
                        <Resistencia>Heladas fuertes (hasta -20째C)</Resistencia>
                </Arbol>
                <Arbol>
                        <NombreCientifico>Quercus ilex</NombreCientifico>
                        <NombreComun>Encina</NombreComun>
                        <Vegetacion>Perenne</Vegetacion>
                        <Altura>En torno a 25 metros</Altura>
                        <Forma>Copa esferica o eliptica irregular. Tronco principal recto. Ramaje tortuoso</Forma>
                        <ColorP>Plateado en hojas jovenes. En hojas antiguas, haz verde oscuro, enves plateado</ColorP>
                        <Resistencia>Heladas fuertes (hasta -15째C)</Resistencia>
                </Arbol>
        </Informacion>
</Arboles>