<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Informacion [
        <!ELEMENT Informacion (Contact, Mail, Sales, Total)>
        <!ELEMENT Contact (BusinessName, Address, Phone, Email, Website)>
        <!ELEMENT BusinessName (#PCDATA)>
        <!ELEMENT Address (Street,City,State,ZipCode)>
        <!ELEMENT Street (#PCDATA)>
        <!ELEMENT City (#PCDATA)>
        <!ELEMENT State (#PCDATA)>
        <!ELEMENT ZipCode (#PCDATA)>
        <!ELEMENT Phone (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Website (#PCDATA)>
        <!ELEMENT Mail (BillTo,ShipTo,Details)>
        <!ELEMENT BillTo (ClientName, Address)>
        <!ELEMENT ClientName (#PCDATA)>
        <!ELEMENT ShipTo (ClientName, Address)>
        <!ELEMENT Details (InvoiceNumber, Date, Terms, DueDate)>
        <!ELEMENT InvoiceNumber (#PCDATA)>
        <!ELEMENT Date (#PCDATA)>
        <!ELEMENT Terms (#PCDATA)>
        <!ELEMENT DueDate (#PCDATA)>
        <!ELEMENT Sales (Type, Description, Qty, Rate, Amount)>
        <!ELEMENT Type (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Qty (#PCDATA)>
        <!ELEMENT Rate (#PCDATA)>
        <!ELEMENT Amount (#PCDATA)>
        <!ELEMENT Total (Subtotal,SalesTax,Shipping,TotalPay)>
        <!ELEMENT Subtotal (#PCDATA)>
        <!ELEMENT SalesTax (#PCDATA)>
        <!ELEMENT Shipping (#PCDATA)>
        <!ELEMENT TotalPay (#PCDATA)>
        ]>

<Informacion>
    <Contact>
        <BusinessName></BusinessName>
        <Address>
            <Street></Street>
            <City></City>
            <State></State>
            <ZipCode></ZipCode>
        </Address>
        <Phone></Phone>
        <Email></Email>
        <Website></Website>
    </Contact>
    <Mail>
        <BillTo>
            <ClientName></ClientName>
            <Address>
                <Street></Street>
                <City></City>
                <State></State>
                <ZipCode></ZipCode>
            </Address>
        </BillTo>
        <ShipTo>
            <ClientName></ClientName>
            <Address>
                <Street></Street>
                <City></City>
                <State></State>
                <ZipCode></ZipCode>
            </Address>
        </ShipTo>
        <Details>
            <InvoiceNumber></InvoiceNumber>
            <Date></Date>
            <Terms></Terms>
            <DueDate></DueDate>
        </Details>
    </Mail>
    <Sales>
        <Type></Type>
        <Description></Description>
        <Qty></Qty>
        <Rate></Rate>
        <Amount></Amount>
    </Sales>
    <Total>
        <Subtotal></Subtotal>
        <SalesTax></SalesTax>
        <Shipping></Shipping>
        <TotalPay></TotalPay>
    </Total>
</Informacion>