<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensaje [
        <!ELEMENT mensaje (remite, destinatario, asunto, texto)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT remite (nombre, email)>
        <!ELEMENT destinatario (nombre, email)>
        <!ELEMENT asunto (#PCDATA)>
        <!ELEMENT parrafo (#PCDATA)>
        <!ELEMENT texto (parrafo)*>
        ]>

<mensaje>
    <remite>
        <nombre>Alfredo Reino</nombre>
        <email>alf@ibium.com</email>
    </remite>
    <destinatario>
        <nombre>Bill Clinton</nombre>
        <email>president@whitehouse.gov</email>
    </destinatario>
    <asunto>Hola Bill</asunto>
    <texto>
        <parrafo>Â¿Hola que tal?</parrafo>
        <parrafo>Hace mucho tiempo que no escribes. A ver si llamas y quedamos pronto.</parrafo>
        <parrafo>un saludo.</parrafo>
    </texto>
</mensaje>